# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stv_project_2.4.7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stv_project_2.4.7
  pod 'TwitterKit'
end
