# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stv-project-2-5-8' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stv-project-2-5-8
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
